#Read the json file generated by the openpose and convert it to the format 
#suitable for the RNN-LSTM network. This conversion takes only the first object 
#detected
import json
import numpy as np
from matplotlib import pyplot as plt
from numpy import array
from numpy import reshape
from pprint import pprint
import glob
from matplotlib.animation import FuncAnimation
import simplejson
from matplotlib import pyplot as plt
import pandas as pd
import cv2
import re
import os

#open('D:/ParamServerContents/KTH_TestTrain/boxing/Test/keypoints/person02_boxing_d1_uncomp_000000000000_keypoints.json').read())
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))


Data_Set_Path = './datasets/UTKinect/'
NJOINTS = 20

#There are two action classes currently being used
action_classes = {'walk':1, 'sit down':2, 'stand up':3, 'pick up':4, 'carry':5, 'throw':6, 'push':7, 'pull':8, 'wave hands':9, 'clap hands':10}

frameCount = {'walk':0, 'sitDown':0, 'standUp':0, 'pickUp':0, 'carry':0, 'throw':0, 'push':0, 'pull':0, 'waveHands':0, 'clapHands':0}

# #body_25 model has 25 Keypoints in the (x,y, confidencemap) format 25 X 3
data= np.empty((NJOINTS, 3))
flist = []
labelFileName = Data_Set_Path + 'actionLabel.txt'
print labelFileName
#Read the actionLabel.txt file
# minlist = []
# maxlist = []
with open(labelFileName,"r") as fp:
	#Read all the video file label information
	
	while True:
		#Read the subject_experiment based filename
		subject = fp.readline().strip()
		if not subject:
			break;
		fileName = Data_Set_Path + 'joints/' + 'joints_' +subject+ '.txt'
		action_list = []
		frameStart_list= []
		frameEnd_list = []
		
		#read the 10 lines mentioning the frame range for each action
		# In actionLabel.txt, the first entry is filename and then frame range for
		# each action
		
		for a in action_classes:
			strdata =  fp.readline()
			action = strdata.split(':')
			action = action[0].strip()
			frames = strdata.split(' ')
			frames_start = 0
			frames_end = 0 
			if(frames[1]!='NaN' and  frames[2]!='NaN'):
				frames_start = int(frames[1].strip())
				frames_end = int(frames[2].strip())
			frameStart_list.append(frames_start)
			frameEnd_list.append(frames_end)
			action_list.append(action)

		frameCount = {'walk':0, 'sitDown':0, 'standUp':0, 'pickUp':0, 'carry':0, 'throw':0, 'push':0, 'pull':0, 'waveHands':0, 'clapHands':0}		
		frameNum = 0 
		with open(fileName) as df:
			while True:
				linedata = df.readline().strip()
				linedata=" ".join(linedata.split())
				linedata = linedata.split(' ')
				if not linedata[0]:
					break
				#print linedata
				frameId = int(linedata[0].strip())
				#find the action label using the frame range in actionLabel.txt
				found  = 0
				index = 0
				#print frameId
				#Scan through the l
				while index < len(action_classes):
					#print index
					if (frameStart_list[index]<= frameId and frameId <= frameEnd_list[index]):
						found = 1
						break;
					index = index + 1
				# print frameStart_list
				# print frameEnd_list
				# print 'Found and FrameID and index',found, frameId,index
				if(found==0):
					continue
				currentActionLabel = action_list[index]
				frameCount[currentActionLabel] += 1
				
		print subject
		print action_list
		print frameStart_list
		print frameEnd_list
		print frameCount
		
		allocated = {'walk':False, 'sitDown':False, 'standUp':False, 'pickUp':False, 'carry':False, 'throw':False, 'push':False, 'pull':False, 'waveHands':False, 'clapHands':False}
		# #print 'subject',subject
		# # #Open the data file 
		# frameNum = 0
		with open(fileName) as df:
		# 	#print 'data reading', fileName
		#  	prevActionLabel = 'beginning'
		  	frameNum = 0;
		  	while True:
		  		linedata = df.readline().strip()
		  		linedata=" ".join(linedata.split())
				
		  		linedata = linedata.split(' ')
		  		if not linedata[0]:
		  			break
				
		  		frameId = int(linedata[0].strip())
				
		  		data_str = linedata[1:];
		  		data = [float(i) for i in data_str]
				
		  		#find the action label using the frame range in actionLabel.txt
		  		found  = 0
		  		index = 0
		 		#Scan through the l
		  		while index < len(frameStart_list):
		  			if (frameStart_list[index]<= frameId and frameId <= frameEnd_list[index]):
		  				found = 1
		  				break;
		  			index = index + 1
		  		if(found==0):
		  			continue
		  		else:
		  			currentActionLabel = action_list[index]
		  			if(allocated[currentActionLabel]==False):
		  	 	 		frameangleMatrix = np.zeros((NJOINTS,NJOINTS,frameCount[currentActionLabel]+5))
		  	 	 		allocated[currentActionLabel]= True
		  	 	 	data =np.array(data)
		  			data =  data.reshape((NJOINTS, 3))

			  		#X_data = data[:,:2]

			  		#Modified by MK on 02-09-2019
			  		X_data = data[:,:1]
			  		X_data2 = data[:,1:2]
			  		X_data3 = data[:,2:3] 
					

	 	 	 		#Extract only the third column
	  		 		#third dimesion is the frame number 
	 	  	 		Zdim = np.ones((NJOINTS,1)) #np.array(data[:,2:]);
	 	  	 		X_data = np.array(X_data) 
	 	  	 		
	 	  	 		#append X_data3
	 	  	 		X_data = np.append(X_data, X_data3,axis=1)

	 	 	 		
	 	  	 		X_data = np.append(X_data, Zdim,axis=1)


	 	 	 		angleMatrix = np.zeros((NJOINTS, NJOINTS))
	 	 	 		for i in range(0,NJOINTS):
			 	 	 	for j in range(0, NJOINTS):
			 	 			angleMatrix[i][j] = angle_between(X_data[i], X_data[j])
			 	 			frameangleMatrix[i][j][frameNum] = angleMatrix[i][j]
			 	 	# minlist.append(angleMatrix.min())
			 	 	# maxlist.append(angleMatrix.max())
			 	 	frameNum += 1
			 	 	if(frameNum >= frameCount[currentActionLabel]):
			 	 		outfile = Data_Set_Path + 'processed/' + subject+'_' + currentActionLabel + '.csv'
			 	 		jsondata ={}
	  	 		 	 	jsondata['FileName']= subject+'_' + currentActionLabel
	  	 		 	 	jsondata['numberofframes'] = frameCount[currentActionLabel]
	  	 		 	 	jsonoutfilename = outfile[:-3]+'json'
	  	 		 	 	with open(jsonoutfilename, 'w') as f:
	  	 		 	 		json.dump(jsondata, f)

			 	 		with file(outfile, 'w') as ofile:
	 				 		for slice2d in frameangleMatrix:
		 			 			np.savetxt(ofile, np.array(slice2d), delimiter=",")
		 			 	frameNum = 0
# print 'Maximum angle is', array(maxlist).max()

# print 'Minimum angle is', array(minlist).min()
